spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: online-service-app
              uri: lb://ONLINE-SERVICE-APP
              predicates:
                - Path=/online/**
              filters:
                - AuthenticationFilter

            - id: restaurant-service
              uri: lb://RESTAURANT-SERVICE
              predicates:
                - Path=/restaurant/**
              filters:
                - AuthenticationFilter

            - id: identity-service
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/auth/**

  application:
    name: ONLINE-SERVICE-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
