server:
  port: 8081

spring:
  application:
    name: ONLINE-SERVICE-APP

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
