apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-auth
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/online_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server-service:8761/eureka/"
  POSTGRES_DB: "online_db"
  POSTGRES_USER: "postgres"
